name: aksaragenerator
description: "Dataset Generator for CNN Handwriting Recognition"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  signature: ^5.4.1
  path_provider: ^2.1.3
  flutter_file_dialog: ^3.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.2.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/handwriting.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
